@HOST = http://localhost
@PORT = 9010
@VERSION = HTTP/1.1
@CONTENT_TYPE = Content-Type: application/json

@FILE_CONTENT_TYPE = Content-Type: multipart/form-data;

### @name GetTomcat
GET {{HOST}}/demo/1475.gif {{VERSION}}

### @name Pic
GET {{HOST}}/upload/common/a82c3d6a-d625-42a0-a277-c37841eb8b88.gif {{VERSION}}

### @name Pic
GET {{HOST}}:{{PORT}}/download/common@a82c3d6a-d625-42a0-a277-c37841eb8b88.gif {{VERSION}}


### @name Upload
POST {{HOST}}:{{PORT}}/upload {{VERSION}}
{{FILE_CONTENT_TYPE}} boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

# ------WebKitFormBoundary7MA4YWxkTrZu0gW
# Content-Disposition: form-data; name="files"

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="files"; filename="1.gif";
Content-Type: image/png

< ./1.gif
------WebKitFormBoundary7MA4YWxkTrZu0gW--
