spring:
  profiles:
    active: @profile.active@
    group:
      dev: nacos,cachee
      prod: nacos,cachee
  datasource:
    url: jdbc:mysql://localhost:3306/dianping?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  web:
    resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/

server:
  port: 9007

mybatis-plus:
  type-aliases-package: com.dianping.entity,com.dianping.dto,
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
