spring:
  application:
    name: gateway

  cloud:
    nacos:
      server-addr: localhost:8848

    gateway:
      routes:
        - id: eureka-m2
          uri: lb://eureka-m2
          predicates:
            - Path=/m2/**
        - id: eureka-m3
          uri: lb://eureka-m3
          predicates:
            - Path=/m3/**
        - id: test
          uri: lb://test
          predicates:
            - Path=/test/**
            - Cookie=code, \d{4}
            - Cookie=x, x
            - Header=x-name
        - id: dianping
          uri: lb://dianping
          predicates:
            - Path=/dianping/**
