spring:
  profiles:
    active: @profile.active@
    group:
      dev: eureka
      prod: eureka
  datasource:
    url: jdbc:mysql://localhost:3306/takeout?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

server:
  port: 9001
