spring:
  datasource:
    url: jdbc:mysql://c_mysql:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true

  redis:
    host: c_redis
